create table aml_transactions (
   id            number generated by default as identity primary key,
   file_id       varchar2(50),
   tx_id         varchar2(50),
   sender_name   varchar2(200),
   receiver_name varchar2(200),
   amount        number(15,2),
   currency      varchar2(10),
   country       varchar2(50),
   tx_date       date,
   status        varchar2(20),
   created_at    date default sysdate
);