create table aml_audit (
   id          number generated by default as identity primary key,
   workflow_id varchar2(100),
   event_type  varchar2(100),
   message     varchar2(1000),
   created_at  date default sysdate
);